# Generated by Django 5.2.9 on 2026-01-09 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_paymentmethod_deposit_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('asset_type', models.CharField(choices=[('share', 'Share'), ('bond', 'Bond')], max_length=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='For Bonds', max_digits=5, null=True)),
                ('maturity_date', models.DateField(blank=True, help_text='For Bonds', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_rate', models.DecimalField(decimal_places=2, help_text='Percentage return (e.g. 15.00)', max_digits=5)),
                ('duration_days', models.IntegerField(help_text='Duration in days')),
                ('status', models.CharField(choices=[('funding', 'Funding'), ('active', 'Active'), ('completed', 'Completed')], default='funding', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('sold', 'Sold')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.project')),
            ],
        ),
    ]
