# Generated by Django 5.2.9 on 2026-01-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_asset_project_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_name',
            field=models.CharField(blank=True, help_text='Optional name for your wallet', max_length=100, null=True),
        ),
    ]
