# Generated by Django 5.2.9 on 2026-01-09 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_withdrawal_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='invest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to invest specifically if multi-deposit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='linked_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_deposits', to='core_app.asset'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_deposits', to='core_app.project'),
        ),
    ]
