# Generated by Django 5.2.9 on 2026-01-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_investmentplan_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='linked_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_deposits', to='core_app.investmentplan'),
        ),
    ]
