# Generated by Django 5.2.9 on 2026-01-10 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_deposit_linked_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trading_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance from shares/bonds profits', max_digits=12),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='last_profit_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
