# Generated by Django 5.2.10 on 2026-01-12 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='referral_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from referral bonuses', max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core_app.account'),
        ),
    ]
